version: '1'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: study-room-dev
    container_name: study-room-node
    volumes:
      - /app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOSTNAME=localhost
      - MONGO_PORT=27017
      - MONGO_DB=studyroom-development
  mongodb:
    image: mongo
    container_name: study-room-mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped