version: '1'
services:
  web:
    build: .
    command:
      - yarn development
    volumes:
      - /app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://localhost:27017

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_USER: go-gps
      - MONGO_DB: user
    ports:
      - 27017:27017
    restart: unless-stopped