name: Node JS CI/CD


on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ]


jobs: 
  test_pull_request: 
    runs-on: ${{matrix.os}}
    strategy: 
    matrix: 
      os: [ubuntu-latest, windows-latest, macOS-lastest]
    
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js

      - uses: actions/setup-node@v1
        with: 
           node-version: '15.4.0'
      - run: yarn install
      - run: yarn run build 
      - run: yarn run test --passWithNoTests

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0

    
